services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-100}'
                WWWUSER: '${WWWUSER:-1000}'
        image: sail-8.4/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8001}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            # - mariadb
    # nginx:
    #     image: nginx:latest
    #     container_name: sail-nginx
    #     ports:
    #         - '8080:80' # Expose Nginx on public port 80
    #         - '443:443' # HTTPS
    #     volumes:
    #          - ./nginx.conf:/etc/nginx/nginx.conf:ro
    #          - ./ssl:/etc/nginx/ssl:ro

    #     # volumes:
    #     #     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # Mount custom Nginx config
    #     #     - .:/var/www/html:ro # Mount application files for static serving
    #     #     - ./ssl:/etc/nginx/ssl:ro # Mount for SSL certificates
    #     depends_on:
    #         - laravel.test
    #     networks:
    #         - sail

    # mariadb:
    #     image: 'mariadb:10.11'
    #     ports:
    #         - '${FORWARD_DB_PORT:-3306}:3306'
    #     environment:
    #         MARIADB_ROOT_PASSWORD: '${DB_PASSWORD}'
    #         MARIADB_ROOT_HOST: '%'
    #         MARIADB_DATABASE: '${DB_DATABASE}'
    #         MARIADB_USER: '${DB_USERNAME}'
    #         MARIADB_PASSWORD: '${DB_PASSWORD}'
    #         MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
    #     volumes:
    #         - 'sail-mysql:/var/lib/mysql'
    #         - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    #     networks:
    #         - sail
    #     healthcheck:
    #         test: ["CMD", "mariadb-admin", "ping", "-p${DB_PASSWORD}"]
    #         retries: 3
    #         timeout: 5s

    mysql:
        image: 'mysql:8.4.5'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}' 
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '${FORWARD_PHPMYADMIN_PORT:-8081}:80'
        environment:
            PMA_HOST: mysql
            PMA_USER: '${DB_USERNAME}'
            PMA_PASSWORD: '${DB_PASSWORD}'
        depends_on:
            - mysql
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    sail-meilisearch:
        driver: local
